// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package config

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (DestinationConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"keyColumns": {
			Default:     "",
			Description: "keyColumns is the configuration of key column names, separated by commas.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"table": {
			Default:     "",
			Description: "table is the configuration of the table name.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"url": {
			Default:     "",
			Description: "url is the configuration of the connection string to connect to ClickHouse database.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
