// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package config

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigKeyColumns = "keyColumns"
	DestinationConfigTable      = "table"
	DestinationConfigUrl        = "url"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigKeyColumns: {
			Default:     "",
			Description: "KeyColumns is the configuration of key column names, separated by commas.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		DestinationConfigTable: {
			Default:     "",
			Description: "Table is the configuration of the table name.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigUrl: {
			Default:     "",
			Description: "URL is the configuration of the connection string to connect to ClickHouse database.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
