// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package config

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (SourceConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"batchSize": {
			Default:     "1000",
			Description: "batchSize is a size of rows batch.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{
				sdk.ValidationGreaterThan{Value: 0},
				sdk.ValidationLessThan{Value: 100001},
			},
		},
		"keyColumns": {
			Default:     "",
			Description: "keyColumns is the configuration of key column names, separated by commas.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"orderingColumn": {
			Default:     "",
			Description: "orderingColumn is a name of a column that the connector will use for ordering rows.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"snapshot": {
			Default:     "true",
			Description: "snapshot is the configuration that determines whether the connector will take a snapshot of the entire table before starting cdc mode.",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
		"table": {
			Default:     "",
			Description: "table is the configuration of the table name.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"url": {
			Default:     "",
			Description: "url is the configuration of the connection string to connect to ClickHouse database.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
